// Generated by scripts/gen-notice.ts from the installed lightweight-charts NOTICE.
// Do not edit by hand. Run `pnpm gen:notice` to regenerate.

export const TRADINGVIEW_NOTICE = "TradingView Lightweight Charts™\nCopyright (с) 2025 TradingView, Inc. https://www.tradingview.com/\n" as const;

export const TRADINGVIEW_ATTRIBUTION_URL = "https://www.tradingview.com/" as const;
