import { existsSync, readFileSync, statSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// Regenerates packages/contracts-abi from the compiled Foundry artifacts. It is
// the only path by which an ABI enters the TypeScript side, so a contract change
// can never leave a stale ABI behind: turbo makes the web and indexer builds
// depend on this task. It never runs forge and never hand-writes an ABI — if an
// artifact is missing or older than its source it stops and tells you to build
// (Addendum E). vm-style differential parity is not this script's job.

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(here, "..");
const repoRoot = resolve(pkgRoot, "..", "..");
const outDir = resolve(repoRoot, "contracts", "out");
const srcDir = resolve(repoRoot, "contracts", "src");

// The four contracts whose ABI the app and indexer consume. No others.
const CONTRACTS = ["Curve", "PeakToken", "PeakpumpFactory", "FeeVault"] as const;

function fail(message: string): never {
  process.stderr.write(`${message}\n`);
  process.exit(1);
}

interface Artifact {
  abi: unknown[];
}

const abis: Record<string, unknown[]> = {};
for (const name of CONTRACTS) {
  const artifactPath = resolve(outDir, `${name}.sol`, `${name}.json`);
  const sourcePath = resolve(srcDir, `${name}.sol`);
  if (!existsSync(artifactPath)) {
    fail(`missing artifact ${artifactPath}\nrun \`forge build\` in contracts/ and try again`);
  }
  // Stale when the source has been touched more recently than the artifact.
  // Compares mtimes only; forge, not this script, decides how to compile.
  if (existsSync(sourcePath) && statSync(sourcePath).mtimeMs > statSync(artifactPath).mtimeMs) {
    fail(`stale artifact ${name}.json (source is newer)\nrun \`forge build\` in contracts/ and try again`);
  }
  const artifact = JSON.parse(readFileSync(artifactPath, "utf8")) as Artifact;
  if (!Array.isArray(artifact.abi)) {
    fail(`artifact ${name}.json has no abi array`);
  }
  abis[name] = artifact.abi;
}

const abiOutDir = resolve(pkgRoot, "abi");
const srcOutDir = resolve(pkgRoot, "src");
mkdirSync(abiOutDir, { recursive: true });
mkdirSync(srcOutDir, { recursive: true });

for (const name of CONTRACTS) {
  writeFileSync(resolve(abiOutDir, `${name}.json`), `${JSON.stringify(abis[name], null, 2)}\n`);
}

// The ABI is inlined as `... as const` rather than imported from the JSON: viem's
// type inference needs the literal in the module, and `as const` cannot apply to
// an imported JSON value. This file is generated; edit gen-abi.ts, not this.
const banner =
  "// Generated by scripts/gen-abi.ts from contracts/out. Do not edit by hand.\n" +
  "// Run `pnpm gen:abi` after any contract change.\n\n";
const body = CONTRACTS.map(
  (name) => `export const ${name}Abi = ${JSON.stringify(abis[name], null, 2)} as const;\n`,
).join("\n");
writeFileSync(resolve(srcOutDir, "index.ts"), banner + body);

process.stdout.write(`wrote ${CONTRACTS.length} ABIs to ${abiOutDir} and ${resolve(srcOutDir, "index.ts")}\n`);
