import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// Emits src/tradingview-notice.generated.ts from the lightweight-charts attribution
// notice. The licence requires the footer to carry that notice transcribed
// verbatim, not copied from any document — so this reads the NOTICE file and
// writes it out untouched. The npm tarball for lightweight-charts omits NOTICE (confirmed for
// 5.2.1: the tarball ships only LICENSE, README and dist), so the file is vendored
// into the repo from the GitHub source tag v5.2.1 and read from vendor/ here. A
// future version bump requires re-vendoring: check the new tag's NOTICE content
// and replace vendor/lightweight-charts-NOTICE before bumping the dependency.

const here = dirname(fileURLToPath(import.meta.url));

const noticePath = resolve(here, "..", "vendor", "lightweight-charts-NOTICE");
if (!existsSync(noticePath)) {
  process.stderr.write(
    `no vendored NOTICE at ${noticePath}\n` +
      "The lightweight-charts licence requires the NOTICE text verbatim and forbids\n" +
      "fabricating or paraphrasing it. Restore vendor/lightweight-charts-NOTICE from\n" +
      "the GitHub source tag matching the installed version and re-run.\n",
  );
  process.exit(1);
}

const notice = readFileSync(noticePath, "utf8");

// The attribution link the notice requires (README: a link to tradingview.com on
// a user-facing page). Kept beside the text so brand.ts renders both together.
const ATTRIBUTION_URL = "https://www.tradingview.com/";

const banner =
  "// Generated by scripts/gen-notice.ts from the installed lightweight-charts NOTICE.\n" +
  "// Do not edit by hand. Run `pnpm gen:notice` to regenerate.\n\n";
const body =
  `export const TRADINGVIEW_NOTICE = ${JSON.stringify(notice)} as const;\n\n` +
  `export const TRADINGVIEW_ATTRIBUTION_URL = ${JSON.stringify(ATTRIBUTION_URL)} as const;\n`;

const outPath = resolve(here, "..", "src", "tradingview-notice.generated.ts");
writeFileSync(outPath, banner + body);
process.stdout.write(`wrote ${outPath}\n`);
